name: integration

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    # Run on external PRs only as the workflow will be already running for the push event on the branch for internal
    # PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory path
        id: pnpm-store-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - name: Setup pnpm store cache
        uses: actions/cache@v2
        id: pnpm-store-cache
        with:
          path: ${{ steps.pnpm-store-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
